#!/usr/bin/env python3
"""Write a project-local Rhino 8 launcher for a prepared site manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


TEMPLATE = '''# Generated by rhino-osm-terrain-modeling. Run with Rhino 8 Python.
import json
import sys
import traceback
from pathlib import Path

SKILL_SCRIPTS = Path(r"{scripts}")
MANIFEST = Path(r"{manifest}")
MODEL = Path(r"{model}")
DIAGNOSTIC = Path(r"{diagnostic}")
ERROR_LOG = Path(r"{error_log}")

if str(SKILL_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SKILL_SCRIPTS))

try:
    from rhino_site_builder import build_site
    report = build_site(MANIFEST, MODEL, DIAGNOSTIC)
    if ERROR_LOG.exists():
        ERROR_LOG.unlink()
    print(json.dumps(report, ensure_ascii=False, indent=2))
except Exception:
    ERROR_LOG.write_text(traceback.format_exc(), encoding="utf-8")
    raise
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--output", type=Path, help="launcher path")
    parser.add_argument("--model", type=Path, help="output .3dm path")
    parser.add_argument("--diagnostic", type=Path, help="output build report path")
    args = parser.parse_args()
    manifest = args.manifest.resolve()
    if not manifest.exists():
        raise SystemExit(f"missing manifest: {manifest}")
    project_dir = manifest.parent
    launcher = (args.output or project_dir / "build_site_in_rhino.py").resolve()
    model = (args.model or project_dir / "site_model.3dm").resolve()
    diagnostic = (args.diagnostic or project_dir / "rhino_build_report.json").resolve()
    error_log = project_dir / "latest_build_error.txt"
    launcher.parent.mkdir(parents=True, exist_ok=True)
    launcher.write_text(TEMPLATE.format(
        scripts=Path(__file__).resolve().parent,
        manifest=manifest,
        model=model,
        diagnostic=diagnostic,
        error_log=error_log.resolve(),
    ), encoding="utf-8")
    print(json.dumps({
        "ok": True,
        "launcher": str(launcher),
        "model": str(model),
        "diagnostic": str(diagnostic),
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
